name: Build nexo SDK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: ${{ fromJson('[''54_0_3'']') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: docker login -u $GITHUB_ACTOR -p ${secrets.GITHUB_TOKEN} ghcr.io

      - name: Build Docker image
        run: docker build . -t nexo-sdk -f src/${{ matrix.version }}/Dockerfile

      - name: Tag Docker image
        run: docker tag nexo-sdk ghcr.io/mateo942/nexo-sdk:${{ matrix.version }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/nexo-sdk:${{ matrix.version }}
