name: Build nexo SDK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: windows-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        version: ${{ fromJson('[''54_0_3'', ''54_0_2'']') }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . -t nexo-sdk -f src/${{ matrix.version }}/Dockerfile

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker image
        run: docker tag nexo-sdk ghcr.io/${{ github.repository_owner }}/nexo-sdk:${{ matrix.version }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/nexo-sdk:${{ matrix.version }}
