name: Hello World on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Print PWD
        run: pwd

      - name: Print LS
        run: ls

      - name: Build Docker image
        run: docker build . -t my-windows-app -f src/54_0_3/Dockerfile

      - name: Print Hello World
        run: echo "Hello, World!"
