name: Build nexo SDK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: windows-latest
    env:
      VERSION: 54_0_3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . -t nexo-sdk -f src/${{ env.VERSION }}/Dockerfile

      - name: Tag Docker image
        run: docker tag nexo-sdk mateo942/nexo-sdk:${{ env.VERSION }}

      - name: Push Docker image
        run: docker push ghcr.io/mateo942/nexo-sdk:${{ env.VERSION }}
